# Caddy Web Server
FROM caddy:2-alpine

# Copia os arquivos pré-compilados localmente para a pasta que o Caddy serve
COPY dist /srv/dist

# Copia o arquivo de configuração do Caddy
COPY Caddyfile /etc/caddy/Caddyfile
